apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
data:
  smtp-server: c210MTguZ21haWwuY29t  # "smtp.gmail.com" encodé en base64
  smtp-port: NTg3                    # "587" encodé en base64
  smtp-username: eW91cmVtYWlsQGdtYWlsLmNvbQ==  # votre adresse e-mail encodée en base64
  smtp-password: <BASE64_ENCODED_PASSWORD>  # votre mot de passe encodé en base64

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-cm
  namespace: argocd
data:
  notifications.yaml: |
    triggers:
      on-sync-succeeded:
        condition: app.status.sync.status == 'Synced'
        template: send-email
    templates:
      send-email:
        body: |
          Application {{ .app.metadata.name }} has been successfully synced!
        title: Application Sync Notification
        recipients:
          - recipient@example.com  # Remplacez par votre adresse e-mail
        smtp:
          host: smtp.gmail.com
          port: 587
          user: <YOUR_SMTP_USER>  # Votre adresse e-mail
          password: <YOUR_SMTP_PASSWORD>  # Votre mot de passe
